# Generated by FlagGems Iluvatar Backend
import logging

import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic

logger = logging.getLogger(__name__)


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def igamma_func(a, x):
    # Compute the regularized lower incomplete gamma function P(a, x) = γ(a,x) / Γ(a)
    # Using series expansion for small x and asymptotic approximation for large x

    zero = 0.0
    one = 1.0

    # Handle edge cases: x <= 0 or a <= 0 returns 0
    valid = (x > zero) & (a > zero)
    result = tl.where(valid, zero, zero)

    # Compute log(x^a * e^(-x)) = a*log(x) - x
    log_x = tl.log(x)
    neg_x = -x
    log_gamma_num = a * log_x + neg_x

    # Gamma(a) approximation using Stirling's formula for large a
    log_a = tl.log(a)
    # Stirling: log(Γ(a)) ≈ (a-0.5)*log(a) - a + 0.5*log(2π) + 1/(12a) - ...
    log_gamma_a = (a - 0.5) * log_a - a + 0.5 * 1.837877 + one / (12.0 * a)
    log_gamma_a = tl.where(a > one, log_gamma_a, zero)

    # For a <= 1, use Γ(a) ≈ 1/a
    log_gamma_a_small = -log_a
    log_gamma_a = tl.where(a <= one, log_gamma_a_small, log_gamma_a)

    # ======== Series expansion (more terms) ========
    # term0: x^a * e^(-x) / (a * Γ(a))
    log_t0 = log_gamma_num - log_a - log_gamma_a
    t0 = tl.exp(log_t0)

    # term1: x^(a+1) * e^(-x) / (a*(a+1) * Γ(a))
    log_t1 = log_gamma_num + log_x - log_a - tl.log(a + one) - log_gamma_a
    t1 = tl.exp(log_t1)

    # term2: x^(a+2)
    log_t2 = log_gamma_num + 2*log_x - log_a - tl.log(a + one) - tl.log(a + 2*one) - log_gamma_a
    t2 = tl.exp(log_t2)

    # term3
    log_t3 = log_gamma_num + 3*log_x - log_a - tl.log(a + one) - tl.log(a + 2*one) - tl.log(a + 3*one) - log_gamma_a
    t3 = tl.exp(log_t3)

    # term4
    log_t4 = log_gamma_num + 4*log_x - log_a - tl.log(a + one) - tl.log(a + 2*one) - tl.log(a + 3*one) - tl.log(a + 4*one) - log_gamma_a
    t4 = tl.exp(log_t4)

    series = t0 + t1 + t2 + t3 + t4

    # ======== Asymptotic approximation for large x ========
    log_q = neg_x + (a - one) * log_x - log_gamma_a
    q = tl.exp(log_q)
    asymp = one - q

    # ======== Choose method ========
    # The boundary x = a is problematic, so use a + 1 as the threshold
    # Use series when x < a + 1
    use_series = x < (a + one)

    # For very small x, just use first few terms
    very_small = x < (a * 0.1)
    result_valid = tl.where(very_small, t0 + t1 + t2,
                           tl.where(use_series, series, asymp))

    # Clamp to valid range [0, 1]
    result = tl.where(valid, tl.clamp(result_valid, zero, one), result)

    return result


def igamma(a, x):
    """Iluvatar specialized implementation of torch.igamma (special.gammainc)"""
    logger.debug("ILUVATAR GEMS igamma")

    if not isinstance(a, torch.Tensor):
        a = torch.tensor(a, dtype=torch.float32)
    if not isinstance(x, torch.Tensor):
        x = torch.tensor(x, dtype=torch.float32)

    # Handle broadcast
    a, x = torch.broadcast_tensors(a, x)

    return igamma_func(a, x)