# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

from flag_gems.ops.special_erfc import special_erfc as _generic_special_erfc
from flag_gems.ops.special_erfc import erfc_ as _generic_erfc_

logger = logging.getLogger("flag_gems." + __name__)


def erfc(x):
    logger.debug("GEMS_METAX ERFC")
    return _generic_special_erfc(x)


def erfc_(x):
    logger.debug("GEMS_METAX ERFC_")
    return _generic_erfc_(x)
