# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import torch

logger = logging.getLogger(__name__)


def as_strided_(self, size, stride, storage_offset=None):
    """In-place view operation that changes tensor shape and stride.

    This operation modifies the tensor's view without copying data.
    It changes the shape, stride, and optionally storage_offset.
    """
    logger.debug("GEMS AS_STRIDED_")

    if storage_offset is None:
        storage_offset = 0

    # Convert to lists if they're tuples
    if isinstance(size, (tuple, torch.Size)):
        size = list(size)
    if isinstance(stride, (tuple, torch.Size)):
        stride = list(stride)

    # Use set_ to change the tensor's view without copying data
    # Use untyped_storage() to avoid the TypedStorage deprecation warning
    self.set_(self.untyped_storage(), storage_offset, size, stride)
    return self
