# Generated by FlagGems: General implementation of igamma (gammainc)
import torch
import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic
from flag_gems.runtime import torch_device_fn


@pointwise_dynamic(promotion_methods=[(0, 1, "DEFAULT")])
@triton.jit
def igamma_func(a, x):
    # Compute the regularized lower incomplete gamma function P(a, x) = γ(a,x) / Γ(a)
    # Using series expansion for small x and asymptotic approximation for large x

    zero = 0.0
    one = 1.0

    # Handle edge cases: x <= 0 or a <= 0 returns 0
    valid = (x > zero) & (a > zero)
    result = tl.where(valid, zero, zero)

    # Compute log(x^a * e^(-x)) = a*log(x) - x
    log_x = tl.log(x)
    neg_x = -x
    log_gamma_num = a * log_x + neg_x

    # Gamma(a) approximation using Stirling's formula for large a
    log_a = tl.log(a)
    log_gamma_a = (a - 0.5) * log_a - a + 0.5 * 1.837877  # log(2π) ≈ 1.837877
    log_gamma_a = tl.where(a > one, log_gamma_a, zero)

    # For a <= 1, use Γ(a) ≈ 1/a
    log_gamma_a_small = -log_a
    log_gamma_a = tl.where(a <= one, log_gamma_a_small, log_gamma_a)

    # Series expansion terms
    log_term1 = log_gamma_num - log_a - log_gamma_a
    term1 = tl.exp(log_term1)

    log_term2 = log_gamma_num + log_x - log_a - tl.log(a + one) - log_gamma_a
    term2 = tl.exp(log_term2)

    log_term3 = log_gamma_num + 2*log_x - log_a - tl.log(a + one) - tl.log(a + 2*one) - log_gamma_a
    term3 = tl.exp(log_term3)

    series = term1 + term2 + term3

    # Asymptotic approximation for large x
    log_q_approx = neg_x + (a - one) * log_x - log_gamma_a
    q_approx = tl.exp(log_q_approx)
    asymp_approx = one - q_approx

    # Choose method based on x vs a
    use_series = x < a

    # For very small x, just use first term
    very_small = x < (a * 0.01)
    result_valid = tl.where(very_small, term1,
                           tl.where(use_series, series, asymp_approx))

    # Clamp to valid range [0, 1]
    result = tl.where(valid, tl.clamp(result_valid, zero, one), result)

    return result


def igamma(a, x):
    """Compute the regularized lower incomplete gamma function.

    This is an alias for torch.special.gammainc.
    """
    if not isinstance(a, torch.Tensor):
        a = torch.tensor(a, dtype=torch.float32, device="cuda")
    if not isinstance(x, torch.Tensor):
        x = torch.tensor(x, dtype=torch.float32, device="cuda")

    # Handle broadcast
    a, x = torch.broadcast_tensors(a, x)

    return igamma_func(a, x)