# Copyright 2026, The FlagOS Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import logging

import triton
import triton.language as tl

from flag_gems.utils import pointwise_dynamic, tl_extra_shim

logger = logging.getLogger("flag_gems." + __name__)

_erfc = tl_extra_shim.erfc


@pointwise_dynamic(promotion_methods=[(0, "INT_TO_FLOAT")])
@triton.jit
def _erfc_kernel(x):
    output = _erfc(x.to(tl.float32))
    return output


def special_erfc(x):
    logger.debug("GEMS SPECIAL_ERFC")
    return _erfc_kernel(x)


# Alias: torch.erfc dispatches to the same implementation
erfc = special_erfc


def erfc_(x):
    logger.debug("GEMS ERFC_")
    return _erfc_kernel(x, out0=x)
