# Generated by KernelGen: https://github.com/flagos-ai/KernelGen
import torch
import triton
import triton.language as tl


@triton.jit
def _special_bessel_y0_kernel(x_ptr, out_ptr, n_elements, BLOCK_SIZE: tl.constexpr):
    pid = tl.program_id(axis=0)
    block_start = pid * BLOCK_SIZE
    offsets = block_start + tl.arange(0, BLOCK_SIZE)
    mask = offsets < n_elements

    x = tl.load(x_ptr + offsets, mask=mask)

    # Compute in fp64 for accuracy/stability, then cast back
    xf = x.to(tl.float64)
    ax = tl.abs(xf)

    # Handle x <= 0 (undefined): return 0
    # For x close to 0, Y0 -> -inf, we return 0 to avoid numerical issues
    zero_threshold = 1e-10
    is_zero = ax < zero_threshold

    # For Y0, use different approximations for different regions:
    # Region 1: 0 < x <= 3 (small x)
    # Region 2: 3 < x <= 8 (medium x)
    # Region 3: x > 8 (large x)

    # Region 1: 0 < x <= 3
    # Using series expansion: Y0(x) = -2/pi * ln(x/2) * J0(x) + (2/pi) * series
    # Simplified polynomial approximation
    is_small = ax <= 3.0

    # Series expansion for small x (0 < x <= 3)
    # This is based on the series: Y0(x) = -2/pi*(ln(x/2)*J0(x) + 0.0776*x^2 + ...)
    t = ax
    t2 = t * t
    t4 = t2 * t2
    # Using approximation from Numerical Recipes / Abramowitz & Stegun
    y0_small = (
        -2.0
        / 3.14159265358979323846
        * (
            0.0
            + t2
            * (
                -6.3211979000000000e-01
                + t2
                * (
                    1.9953730240000000e-01
                    + t2
                    * (
                        -5.5562058260000000e-02
                        + t2
                        * (
                            8.9413673000000000e-03
                            + t2
                            * (
                                -8.5149150000000000e-04
                                + t2
                                * (
                                    4.7946400e-05
                                    + t2 * (-1.584420e-06 + t2 * 2.63230e-08)
                                )
                            )
                        )
                    )
                )
            )
        )
    )

    # Add the logarithmic singularity term for small x
    # Y0 has a logarithmic singularity at x=0: Y0(x) ~ (2/pi) * ln(x/2)
    log_term = tl.log(ax / 2.0)
    # J0(x) approximation for small x
    j0_small = (
        1.0
        + t2
        * (
            -2.2492797e-01
            + t2
            * (
                3.1971593e-02
                + t2
                * (
                    -2.4880297e-03
                    + t2 * (1.465519e-04 + t2 * -5.944e-06)
                )
            )
        )
    )
    # Y0(x) ~ -2/pi * ln(x/2) * J0(x) + series
    log_contribution = -2.0 / 3.14159265358979323846 * log_term * j0_small
    y0_small = y0_small + log_contribution

    # Region 2: 3 < x <= 8 (medium x) and Region 3: x > 8 (large x)
    # Use asymptotic expansion: Y0(x) ~ sqrt(2/pi/x) * (sin(x-pi/4) + 1/(8x)*cos(x-pi/4) - ...)
    is_medium = (ax > 3.0) & (ax <= 8.0)

    # For medium x (3 < x <= 8)
    t = 3.0 / ax
    sin_term = tl.sin(ax - 3.14159265358979323846 / 4.0)
    cos_term = tl.cos(ax - 3.14159265358979323846 / 4.0)
    asymptotic = tl.sqrt(2.0 / 3.14159265358979323846 / ax)

    # Asymptotic series for Y0
    y0_large = asymptotic * (
        sin_term
        + t
        * (
            -8.380678e-02
            + t
            * (
                7.2140e-03
                + t
                * (
                    -1.348e-02 + t * (5.38e-03 + t * (-8.58e-04 + t * 3.34e-05))
                )
            )
        )
    )

    # Add 1/(8x) correction term
    correction = cos_term / (8.0 * ax)
    y0_large = y0_large + asymptotic * correction

    # Combine results
    y = tl.where(is_small, y0_small, y0_large)
    y = tl.where(is_zero, tl.cast(0.0, y.dtype), y)

    # Cast back to input dtype for storage
    y = y.to(x.dtype)
    tl.store(out_ptr + offsets, y, mask=mask)


def _run_special_bessel_y0_kernel(x: torch.Tensor, out: torch.Tensor):
    assert x.is_cuda and out.is_cuda, "Tensors must be CUDA tensors"
    assert x.dtype in (
        torch.float16,
        torch.bfloat16,
        torch.float32,
        torch.float64,
    ), "Unsupported dtype"
    assert out.dtype == x.dtype, "Output dtype must match input dtype"

    x_c = x.contiguous()
    out_c = out.contiguous()

    n_elements = out_c.numel()
    if n_elements == 0:
        return out

    grid = lambda meta: (triton.cdiv(n_elements, meta["BLOCK_SIZE"]),)
    _special_bessel_y0_kernel[grid](x_c, out_c, n_elements, BLOCK_SIZE=1024)

    if out_c.data_ptr() != out.data_ptr():
        out.copy_(out_c)
    return out


def special_bessel_y0(x: torch.Tensor):
    """
    ATen wrapper: special_bessel_y0(Tensor self) -> Tensor
    """
    out = torch.empty_like(x)
    return _run_special_bessel_y0_kernel(x, out)


def special_bessel_y0_out(x: torch.Tensor, out: torch.Tensor):
    """
    ATen wrapper: special_bessel_y0.out(Tensor self, Tensor out) -> Tensor
    """
    # Broadcast input to out's shape if needed
    if x.shape != out.shape:
        x = x.expand(out.shape)
    _run_special_bessel_y0_kernel(x, out)
    return out